### ISSUE TITLE
iOS support 

### ISSUE THREAD

**Issue by Shusek** [joffrey-bion/krossbow#126]
**Problem/use case that this feature is meant to solve/enable**
 would like the library to support multiplatformity more by adding support for iOS. 

**Describe the solution you'd like**
After this issue will be resolved we can use ktor library without additional changes.
https://github.com/ktorio/ktor/issues/1894

**Describe alternatives you've considered**
(Is there a way -maybe inconvenient- to achieve your goal at the moment, or a workaround?)
At this moment websocket on ios ktor client is not supported (posix is not supported). We can use workaround it by publish separate ios module with client looks like:
https://github.com/ln-12/kmm-websocket/blob/main/shared/src/iosMain/kotlin/com/jetbrains/handson/kmm/shared/network/PlatformSocket.kt 

We can also choose not to do this and treat this issue as a placeholder.

**Comment by joffrey-bion** [comment]
That would be nice indeed, but I think the reason why the Ktor team is waiting is because coroutines on native are still lacking multithreading. I'm not sure if there is a non-blocking way at the moment to read from the TCP connection, so maybe that's why it makes things more complicated.

I will definitely try and see if there is at least something I can do about it in this repo, I would love to add support for native so Krossbow is fully multiplatform.
In any case, I think the minimum I could do is compile for native even without any websocket implementation. This way, users can still provide their own, as long as they implement Krossbow's `WebSocketClient` interface.

**Comment by joffrey-bion** [comment]
Finally done! I hope this will be useful 🙂
