### ISSUE TITLE
Use the library in Kotlin/js multiplatform project

### ISSUE THREAD

**Issue by Romixery** [joffrey-bion/krossbow#189]
**Describe the bug**

Hi,
I have trouble when I want to compile Kotlin/JS project that contains the library. It seems the library is not prepared for the JS platform at all.

**Reproduction and additional details**
My current `build.gradle.kts` configurations:
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/11367383/156810911-b3f18114-af7d-4010-a2a1-b95c7ce3cc2c.png">

**The Error**
After run `./gradlew jsBrowserRun --continuous`, I'm getting these errors!

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/11367383/156810653-d23b6299-4745-46f8-8bf1-7516bc89667b.png">

**Context**

* Krossbow version: 3.1.1
* Kotlin version: 1.6
* Kotlin target(s): Kotlin/JS

Artifacts used:
- [ ] `krossbow-stomp-core`
- [ ] `krossbow-stomp-jackson`
- [ ] `krossbow-stomp-kxserialization`
- [ ] `krossbow-websocket-core`
- [ ] `krossbow-websocket-sockjs`
- [ ] `krossbow-websocket-spring`
- [ ] `krossbow-websocket-okhttp`
- [x] `krossbow-websocket-ktor`

**Comment by joffrey-bion** [comment]
Hi, thanks a lot for the report! 

You're using the JS IR compiler here, and Krossbow hasn't been release for IR yet (only the legacy JS). I intend to release a version for the IR compiler as soon as Kotlin 1.6.20 is out, because there are some blocking issues for now that will be resolved in that Kotlin version. Please follow https://github.com/joffrey-bion/krossbow/issues/98 to track this.
