### ISSUE TITLE
extra HTTP headers for connect frame (for passing auth token or other)

### ISSUE THREAD

**Issue by Mostrapotski** [joffrey-bion/krossbow#64]
Hello,
I need to send additional data in the connect frame (device-id and token). 
It is not stated forbidden (nor allowed) in the stomp protocol documentation, but unfortunately some servers are expecting values here. 
I see you do not allow custom header for that frame, is that intentional, or maybe you didn't have the use case yet ?

If you accept, i can do a PR to edit `WebSocketSession.stompConnect`and `StompClient.connect` functions. 

Additionally, THANK YOU for such a great work on this modern library.

**Comment by joffrey-bion** [comment]
Hey, thanks for opening this issue. Indeed the spec doesn't allow not forbid additional headers in the STOMP/CONNECT frame. This is likely an oversight in the spec, and also on my part then 😄 
To be honest I didn't have the use case yet myself, but it can definitely be added.

I think it will need more than just changes in these functions. For instance, we should also allow custom headers in `StompConnectHeaders` just like in `StompSendHeaders`.
Now maybe it will be a bit annoying to provide an overload taking the raw headers object as an argument on the `StompClient`, because some of them are actually computed automatically (host and heartbeats), but yes, adding a map argument defaulting to empty map here would be a good enough solution at least for now.

**Comment by joffrey-bion** [comment]
Released as part of version 0.31.0.

**Comment by joffrey-bion** [comment]
@Mostrapotski out of curiosity, which platform are you using Krossbow on? What's your use case?

**Comment by Mostrapotski** [comment]
I work for a French retailer (red branding, I believe you can guess who it
is!)

When entering the store, you can scan a loyalty card on a tablet to unlock
a wireless device that you can pick up.
While shopping and adding products to your basket, use the wireless device
to scan barcodes.

Before leaving the store, just put the wireless device back, use the tablet
to pay.

We have APIs for the tablet and each wireless devices, and also a stomp
server.
Needless to say between http long polling and your exquisite kotlin lib,
the choice was a no brainer.

Custom header are needed in the connect frame to identify tablets and
wireless devices. We also have a jwt token for Auth.

As a side note, you should consider adding a donate button.

**Comment by Mostrapotski** [comment]
Forgot to say it's all android.
