### ISSUE TITLE
Kotlin serialization rc2

### ISSUE THREAD

**Issue by Shusshu** [joffrey-bion/krossbow#70]
https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.0.0-RC2

**Comment by joffrey-bion** [comment]
The dependency is upgraded in the `0.42.0` release.
Please let me know if you face any issue.

Also, note that if you were using the JSON serialization format, you will now need an extra `kotlinx-serialization-json` dependency.
This is due to the new artifact breakdown in Kotlinx Serialization 1.0.0-RC2 (please see the release notes you linked for more details).
